Validate safeguards config
serverless/safeguards-plugin pull request #20
Opened 2020-12-20 17:09 UTC by Kamahl19

This adds validation of the `custom.safeguards` config. 

However because of https://github.com/serverless/safeguards-plugin/issues/14 and https://github.com/serverless/enterprise-plugin/issues/521 it will not validate the config yet because the enterprise-plugin is currently overriding the `custom.safeguards` validation.

2020-12-21 12:44 UTC, Kamahl19 commented
@medikoo Would you care to merge this one as well? It wont do anything until the schema is removed from enterprise-plugin but after that, it will start properly validating the safeguards config.

2020-12-21 12:54 UTC, medikoo requested changes
@Kamahl19 that looks good, still please consider one suggestion I've proposed

2020-12-21 12:54 UTC, medikoo commented on index.js
> +    this.sls.configSchemaHandler.defineCustomProperties({
Let's assign it only if `custom.safeguards` are not defined. I think we can confirm on it by inspecting `this.sls.configSchemaHandler.schema`

(we plan to introduce crashing if there's an attempt to override existing schema, it shouldn't be silent)

2020-12-21 13:16 UTC, Kamahl19 commented on index.js
> +    this.sls.configSchemaHandler.defineCustomProperties({
I am not sure it's a good idea to only assign this if `custom.safeguards` is not defined. Then, once you make `defineCustomProperties` throw/warn when overriding the schema, it wont throw in this case because of `if`. And once you remove the schema from enterprise plugin, the `if` condition will be left here useless and forgotten :) 

Imho the schema from enterprise should be removed (either in next major or right now as it confuses users), then (or right now) this should be merged as is, and then `defineCustomProperties` should throw in next major version if overwriting.

2020-12-21 15:27 UTC, medikoo commented on index.js
> +    this.sls.configSchemaHandler.defineCustomProperties({
> I am not sure it's a good idea to only assign this if custom.safeguards is not defined. Then, once you make defineCustomProperties throw/warn when overriding the schema, it wont throw

Yes, we don't want it to throw, as it'll make plugin not unusable. Technically it's just a warning, and in this case we know this error is not harmful, there's no point converting this into crash

2020-12-23 12:37 UTC, Kamahl19 commented
@medikoo i think we can merge this one now, right?

2020-12-23 12:38 UTC, medikoo commented
> @medikoo i think we can merge this one now, right?

I think all concerns from a review were not addressed yet. Please re-request review when that's done, and then we'll definitely merge it

2020-12-23 16:37 UTC, Kamahl19 commented
@medikoo Do you mean to do this?
```
Let's assign it only if custom.safeguards are not defined. I think we can confirm on it by inspecting this.sls.configSchemaHandler.schema
```

I was thinking we dont want to do this as enterprise plugin is not defining the safeguards schema anymore. Do other plugins check before assigning a schema? If not, I wouldnt add it here neither.

2020-12-23 16:42 UTC, medikoo commented
> I was thinking we dont want to do this as enterprise plugin is not defining the safeguards schema anymore. 

We do not have guarantee that next version of this plugin will be used with a Framework that has next version of enterprise plugin installed

> Do other plugins check before assigning a schema? If not, I wouldnt add it here neither.

Here we deal with special case, where we're aware of collision that we want to handle gently. I'm not aware of any other plugins dealing with such case.

2020-12-25 12:40 UTC, Kamahl19 commented
@medikoo When I log `this.sls.configSchemaHandler.schema.custom` in here https://github.com/serverless/safeguards-plugin/blob/7d6f53c2e703412b81c196517a58920f624a9e54/index.js#L59 it is 
```
{
  "type": "object",
  "properties": {},
  "required": []
}
```

2020-12-28 09:02 UTC, medikoo commented
> but I believe enterprise-plugin is being applied AFTER safeguards plugin 

Indeed, that's the case, and we cannot work around this easily. Ok let's take it as it is, for safety we'll just release this with major version bumped, and bump peer dependency version of a `serverless` to next one (one that'll come with updated `@serverless/enterprise-plugin`)

2020-12-28 09:02 UTC, medikoo approved these changes
Thank you @Kamahl19 !

2020-12-28 09:05 UTC, merged