add option to just validate
serverless/safeguards-plugin pull request #5
Opened 2020-08-27 08:22 UTC by deitch

Resolves part of #4 

Enables you to call `serverless safeguards validate` and it will just validate the policy, returning the results. If it passes, will exit with 0, else 1. Supports `--stage=<stage>`.

Because the policy is applied to the compiled package, not the input serverless.yaml, it packages everything up first.

2020-08-27 08:28 UTC, deitch commented
Fixed the formatting issue.

2020-08-27 09:30 UTC, deitch commented
no idea why the lint is failing. I ran it locally, all good. Can you rerun it?

2020-08-27 11:04 UTC, medikoo reviewed
> no idea why the lint is failing. I ran it locally, all good. Can you rerun it?

It's due to changes in actions/checkout. I've updated `master` with workaround that fixes that. Can you merge with `master`?

2020-08-27 12:15 UTC, deitch commented
Sure. Rebased and pushed.

2020-08-27 12:25 UTC, deitch commented
That got it past the previous error. It wants a consistent-return, so I just had it `return null`, but I do not know if the hooks system insists on something else.

2020-08-27 12:30 UTC, deitch commented
That cleared it up. codecov is unhappy about the changes though.

2020-08-27 12:35 UTC, medikoo approved these changes
Thank you @deitch !

> codecov is unhappy about the changes though.

It's not a required check, and it's not trivial to test it properly, so let's ignore that

2020-08-27 12:36 UTC, medikoo requested changes
It'll be good though. To document new command

Can you add some documentation to main README?

2020-08-27 12:36 UTC, deitch commented
Sure, will do.

2020-08-27 12:37 UTC, medikoo commented on index.js
> +    return null;
To avoid enforced `return`, you may make this funtion `async`, and simply `await` spawned packaging

2020-08-27 12:41 UTC, deitch commented
I added some info to the README.md

2020-08-27 12:41 UTC, deitch commented on index.js
> +    return null;
What would that look like?

2020-08-27 12:47 UTC, medikoo commented on index.js
> +    return null;
```javascript
async doPackage() {
  // must ensure packaging is done before doing policy
  if (!this.options.package && !this.sls.service.package.path) {
    await this.sls.pluginManager.spawn('package');
  }
}
```

2020-08-27 12:50 UTC, deitch commented on index.js
> +    return null;
Oh that was what you meant? I thought something with the hooks. OK fine. Thanks

2020-08-27 12:58 UTC, deitch commented on index.js
> +    return null;
Took your suggestion precisely. Thanks!

2020-08-28 09:08 UTC, deitch commented
How does that look?

2020-08-28 12:01 UTC, medikoo approved these changes
Looks great, thank you @deitch !

2020-08-28 12:01 UTC, merged

2020-08-28 12:02 UTC, deitch commented
Huzzah!

I will get you a PR on additional separate policy files soon.