additional policy available
serverless/safeguards-plugin pull request #7
Opened 2020-08-30 15:10 UTC by deitch

As discussed with @medikoo in #4 

Fixes #4 

@medikoo it supports a single `--policy-file` and multiple `--policy-file` (as well as none, of course). I did *not* implement retrofitting the `--policy-file` option to `sls deploy`, as it is another layer and more complex. We always can open another PR to add that in later.

Looking forward to your response.

2020-08-31 10:59 UTC, medikoo requested changes
Thank you @deitch that looks very promising! Please see my remarks

2020-08-31 10:59 UTC, medikoo commented on safeguards/index.js
> +  const pFiles = concat([], policyFiles);
API design-wise I think it'll be cleaner if we unconditionally expect here _array_ input (it's consumer that should pass eventually pass single value input in an array)

2020-08-31 10:59 UTC, medikoo commented on safeguards/index.js
> +      return get(data, 'custom.safeguards') || [];
I'd expect policies to be exported directly in policy file. What's the point in nesting then in `custom.safeguards` structure?

2020-08-31 10:59 UTC, medikoo commented on safeguards/parse.js
> +  }
This `try/catch` seems superfluous. As in `parse` function we anyway _throw_ eventual parsing error. It'll be cleaner to simply throw it here

2020-08-31 10:59 UTC, medikoo commented on safeguards/parse.js
> +    return jc.parse(contents);
Do we have a use case of using cyclic references in Safeguards?

Why simple `JSON.parse` is not good enough?

2020-08-31 10:59 UTC, medikoo commented on safeguards/parse.js
> +  return contents.toString().trim();
Shouldn't we crash in that case? It doesn't seem that we support plain string input down the way

2020-08-31 10:59 UTC, medikoo commented on safeguards/index.js
> +  const sg2 = ctx.extendedPolicies || [];
I think it'll be nice if we use meaningful variable names. Can we name it `safeguards` an `extendedPolicies` ?

2020-08-31 10:59 UTC, medikoo commented on README.md
> +- **Enforceable** - You can run the `safeguards validate` command while specifying additional policy files in addition to policies specified in serveless.yaml.
`serverless.yml`

2020-08-31 11:04 UTC, deitch commented
> Please see my remarks

Will do.

2020-08-31 11:05 UTC, deitch commented on README.md
> +- **Enforceable** - You can run the `safeguards validate` command while specifying additional policy files in addition to policies specified in serveless.yaml.
Oops.

2020-08-31 11:05 UTC, deitch commented on README.md
> +- **Enforceable** - You can run the `safeguards validate` command while specifying additional policy files in addition to policies specified in serveless.yaml.
Resolved.

2020-08-31 11:06 UTC, deitch commented on safeguards/index.js
> +  const sg2 = ctx.extendedPolicies || [];
I don't understand the comment here. The first line is what was there before, just reading the `custom.safeguards` from the actual `serverless.yaml` config file. The second line is reading the extended policies from the context, where the earlier section loaded it.

What do you mean to name it differently? Isn't the `ctx` actually the safeguards context?

2020-08-31 11:07 UTC, deitch commented on safeguards/index.js
> +  const pFiles = concat([], policyFiles);
I am ok with that. Fixing.

2020-08-31 11:09 UTC, deitch commented on safeguards/index.js
> +  const pFiles = concat([], policyFiles);
Done

2020-08-31 11:09 UTC, deitch commented on safeguards/index.js
> +      return get(data, 'custom.safeguards') || [];
That is a good question. I was trying to make the policy files look precisely like the regular `serverless.yaml` file. If you are OK with it just being policies, I can change it. 

Is that your preference?

2020-08-31 11:13 UTC, deitch commented on safeguards/parse.js
> +  }
I actually copied this almost identically from the safeguards core. 

This makes it _much_ cleaner. Got rid of the whole `loadYAML` function.

2020-08-31 11:13 UTC, deitch commented on safeguards/parse.js
> +  return contents.toString().trim();
Sure, we can just throw an error there.

2020-08-31 11:14 UTC, deitch commented on safeguards/parse.js
> +  return contents.toString().trim();
Done

2020-08-31 11:15 UTC, deitch commented on safeguards/parse.js
> +    return jc.parse(contents);
No idea. I just took it from the core of safeguards. If you are ok with it, I can make it a simple `JSON.parse`?

2020-08-31 11:15 UTC, deitch commented
Some open questions for you.

2020-08-31 11:24 UTC, medikoo commented on safeguards/index.js
> +  const sg2 = ctx.extendedPolicies || [];
I meant that variable names as `sg1` and `sg2` are not self explanatory. We should also not use abbreviations

2020-08-31 11:25 UTC, medikoo commented on safeguards/index.js
> +      return get(data, 'custom.safeguards') || [];
> Is that your preference?

I think its' more about, what's more natural, and expected by users (?) :)

In my eyes it's natural to assume that `policies.yml` contains list of _policies_ and not full service config with eventual policies configurations (but maybe I miss something)

2020-08-31 11:26 UTC, deitch commented on safeguards/index.js
> +  const sg2 = ctx.extendedPolicies || [];
Ah, that? Sure.

2020-08-31 11:26 UTC, medikoo commented on safeguards/parse.js
> +    return jc.parse(contents);
Totally. It could be copied from place where indeed handling circular reference could back a valid use case, but I don't see one here.

2020-08-31 11:27 UTC, deitch commented on safeguards/index.js
> +  const sg2 = ctx.extendedPolicies || [];
Done. Made it even more verbose. :-)

2020-08-31 11:27 UTC, deitch commented on safeguards/index.js
> +      return get(data, 'custom.safeguards') || [];
I agree. I didn't want to assume too much about a piece of software for which I am a relatively new contributor. I will update it.

2020-08-31 11:33 UTC, deitch commented on safeguards/index.js
> +      return get(data, 'custom.safeguards') || [];
Done. Updated the README as well and tested with several policy files.

2020-08-31 11:33 UTC, deitch commented on safeguards/parse.js
> +    return jc.parse(contents);
Made a simple `JSON.parse`, and also removed from `package.json`

2020-08-31 11:34 UTC, deitch commented
I think we got all of your comments. Take a fresh look please @medikoo

2020-09-01 07:41 UTC, medikoo reviewed
@deitch thank you! It looks really good. I've proposed few last minor suggestions

2020-09-01 07:41 UTC, medikoo commented on index.js
> +      this.extendedPolicies = await loadPolicyFiles(concat([], policyFile));
Let's fallback to lodash only if there's no convenient native counterpart. While here we can simply to `[].concat(policyFile)`

2020-09-01 07:41 UTC, medikoo commented on safeguards/index.js
> +  const configFileDefinedSafeguards = get(ctx.sls.service, 'custom.safeguards') || [];
I think it's `custom.safeguards.policies`

2020-09-01 07:41 UTC, medikoo commented on safeguards/index.js
> +  const policyConfigs = concat(configFileDefinedSafeguards, extendedPolicies).map(policyProcessor);
`configFileDefinedSafeguards` is guaranteed to be an array here, so we can do `configFileDefinedSafeguards.concat(extendedPolicies)`

2020-09-01 07:41 UTC, medikoo commented on safeguards/parse.js
> +  throw new Error('unknown file format');
It'll be nice to use `new this.serverless.classes.Error`, this will signal it's an _operational_ error (not _programmer_ error).

Also then it'll be nice to have error message improved to something as:`Unrecognized format of "${filename}". Policies can be provided either via YAML or JSON files`

2020-09-01 08:19 UTC, deitch commented on safeguards/index.js
> +  const policyConfigs = concat(configFileDefinedSafeguards, extendedPolicies).map(policyProcessor);
Good point. Keeps it cleaner.

2020-09-01 08:20 UTC, deitch commented on safeguards/index.js
> +  const configFileDefinedSafeguards = get(ctx.sls.service, 'custom.safeguards') || [];
I don't think so. Here was the old line:

```go
  const policyConfigs = (get(ctx.sls.service, 'custom.safeguards') || []).map((policy) => {
```

2020-09-01 08:20 UTC, deitch commented on index.js
> +      this.extendedPolicies = await loadPolicyFiles(concat([], policyFile));
Sure, keeps it clean.

2020-09-01 08:39 UTC, deitch commented on safeguards/parse.js
> +  throw new Error('unknown file format');
parse itself is fairly clean, doesn't have the context of `this`, but it is only consumed in `loadPolicyFile`, so easy to catch there. Updated, take a look.

2020-09-01 09:34 UTC, medikoo commented on safeguards/index.js
> +  const configFileDefinedSafeguards = get(ctx.sls.service, 'custom.safeguards') || [];
Indeed, it's in plugin v3.8 where it was expect to be at `custom.enterprise.safeguards.policies`: https://github.com/serverless/enterprise-plugin/blob/v3.8.1/lib/safeguards/index.js#L42

Sorry for confusion

2020-09-01 09:38 UTC, medikoo commented on index.js
> +    if (policyFile !== '') {
Let's simplify it to more natural notation:

```
const policyFile = this.options['policy-file'
if (policyFile) {
```

2020-09-01 09:38 UTC, medikoo commented on safeguards/index.js
> +        throw new ctx.sls.classes.Error(error.message);
This is not great as it'll convert eventual _programmer_ errors to _operational_ ones. 

I believe correct way is to make `parse` to specifically decide on error type. Blindly assuming that all `parse` errors are operational, is error-prone (DX wise)

2020-09-01 09:45 UTC, deitch commented on index.js
> +    if (policyFile !== '') {
I am not sure what you were trying to write here; the comment got chopped off.

2020-09-01 09:46 UTC, deitch commented on safeguards/index.js
> +        throw new ctx.sls.classes.Error(error.message);
Fair enough, but I didn't like the idea of passing the context into what is a clean parse function. Right now, parse is really clean, just:

```js
function parse(filePath, contents) {
  // Auto-parse JSON
  if (filePath.endsWith('.json')) {
    return JSON.parse(contents);
  } else if (filePath.endsWith('.yml') || filePath.endsWith('.yaml')) {
    const options = {
      filename: filePath,
    };
    return YAML.load(contents.toString(), options || {});
  }
  throw new Error(
    `Unrecognized format of "${filePath}". Policies can be provided either via YAML or JSON files`
  );
}
```

To do what you suggested, we would need to pass in the context, which makes a generic, nice and clean `parse` function (in a module) into something tightly tied to it.

2020-09-01 10:59 UTC, medikoo commented on index.js
> +    if (policyFile !== '') {
I mean to do:

```javascript
const policyFile = this.options['policy-file']
if (policyFile) {
```

Instead of  https://github.com/serverless/safeguards-plugin/blob/44cb48c93f0b1d0575a163e52268eb1ead5ece56/index.js#L79-L81

Falling back to empty string, doesn't seem to add any value here

2020-09-01 11:01 UTC, medikoo commented on safeguards/index.js
> +        throw new ctx.sls.classes.Error(error.message);
That's true, in that case it should be rather a method of plugin, there's probably no other way to achieve that cleanly

2020-09-01 11:43 UTC, deitch commented on index.js
> +    if (policyFile !== '') {
Oh, ok. It doesn't bother me.

2020-09-01 11:45 UTC, deitch commented on index.js
> +    if (policyFile !== '') {
Fixed

2020-09-01 11:45 UTC, deitch commented on safeguards/index.js
> +        throw new ctx.sls.classes.Error(error.message);
OK

2020-09-01 11:50 UTC, deitch commented on safeguards/index.js
> +        throw new ctx.sls.classes.Error(error.message);
I gave up and passed it the context. Done.

2020-09-01 11:50 UTC, deitch commented
Addressed all of your comments. Back to you @medikoo

2020-09-01 12:16 UTC, medikoo approved these changes
Thank you @deitch !

2020-09-01 12:17 UTC, merged

2020-09-01 12:19 UTC, deitch commented
Excellent! Thanks @medikoo !